<?php

return array(
    'slug' => 'ai-news-editor',
    'title' => 'WSH AI News Editor PRO',
    'needles' => array('WSH AI News Editor'),
    'fields' => array(
        'landing_hero_label' => 'WSH AI News Editor PRO',
        'landing_hero_title' => 'Your AI editorial assistant for WordPress',
        'landing_hero_text' => 'Rewrite, summarize, translate and optimize news and editorial content directly inside WordPress, without breaking your publishing workflow.',
        'landing_hero_primary' => 'Get PRO license',
        'landing_hero_secondary' => 'See all features',
        'landing_needs_label' => 'Why publishers need more than a generic AI writer',
        'landing_needs_title' => 'Copy-paste AI tools slow down real editorial workflows.',
        'landing_needs_text' => 'Your writers and editors already work in WordPress. WSH AI News Editor PRO brings practical AI tools into that environment so teams can improve existing stories, prepare headlines, summaries and translations, and review the result before publishing.',
        'landing_features_label' => 'Features',
        'landing_features_title' => 'AI tools built around the WordPress editorial workflow',
        'landing_features_text' => 'WSH AI News Editor PRO focuses on the repetitive editorial tasks that consume time every day. Editors remain in control of the final text while AI helps accelerate preparation and revision.',
        'landing_preview_label' => 'Preview',
        'landing_preview_title' => 'An AI workspace your editorial team can use without leaving WordPress',
        'landing_preview_text' => 'Keep the article, AI actions and generated result in one workflow. Editors choose an action, review the generated version and decide what should be applied to the post.',
        'landing_compare_label' => 'Free vs PRO',
        'landing_compare_title' => 'Start with essential AI assistance. Unlock the full editorial workflow with PRO.',
        'landing_compare_text' => 'The free edition covers basic rewriting. PRO adds headlines, summaries, translation, meta descriptions and the review workflow a newsroom needs.',
        'landing_compare_free' => 'WSH AI News Editor (Free)',
        'landing_compare_pro' => 'WSH AI News Editor PRO',
        'landing_market_label' => 'Compare plugins',
        'landing_market_title' => 'How WSH AI News Editor PRO fits into the AI writing market',
        'landing_market_text' => 'This is not a replacement for a broad AI platform. It is built for newsroom and publisher workflows inside WordPress: editing existing content, producing editorial variants and keeping human review at the center.',
        'landing_market_ours' => 'WSH AI News Editor PRO',
        'landing_market_competitor_a' => 'Generic AI writer plugins',
        'landing_market_competitor_b' => 'External AI chat tools',
        'landing_pricing_label' => 'Pricing',
        'landing_pricing_title' => 'Choose your WSH AI News Editor PRO license',
        'landing_pricing_text' => 'Simple annual licenses with updates and support included. If the plugin uses your own AI provider key, provider usage fees stay separate from the license.',
        'landing_faq_label' => 'Frequently Asked Questions',
        'landing_faq_title' => 'Getting started with WSH AI News Editor PRO',
        'landing_faq_button' => 'See more',
    ),
    'needs' => array(
        'You want to rewrite or improve an article without moving content between WordPress and external AI tools.',
        'You need multiple headline ideas quickly for breaking news, features and evergreen stories.',
        'You regularly turn long articles into excerpts, summaries or shorter versions.',
        'You publish for multiple audiences and need faster translation and localization workflows.',
        'You want consistent tone and editorial style across writers and contributors.',
        'You want AI to assist editors, not publish uncontrolled content automatically.',
    ),
    'features' => array(
        array('tag' => 'Rewrite', 'title' => 'AI article rewriting', 'text' => 'Rewrite existing articles while preserving the original topic and editorial intent. Useful for improving clarity, restructuring drafts and preparing alternative versions.'),
        array('tag' => 'Headlines', 'title' => 'Headline generator', 'text' => 'Generate multiple headline variations from an existing story so editors can compare angles and choose the best fit.'),
        array('tag' => 'Summaries', 'title' => 'Smart summaries and excerpts', 'text' => 'Turn long-form stories into concise summaries, archive excerpts, newsletter snippets or shorter editorial versions without leaving WordPress.'),
        array('tag' => 'Style', 'title' => 'Tone and style control', 'text' => 'Adapt copy for professional, neutral, formal, concise or publication-specific styles while the editor stays responsible for the final version.'),
        array('tag' => 'Translation', 'title' => 'AI-assisted translation', 'text' => 'Translate and adapt editorial content for additional languages from the WordPress workflow, then review the result before publication.'),
        array('tag' => 'SEO', 'title' => 'Meta descriptions and content optimization', 'text' => 'Generate concise meta descriptions, improve article structure and prepare supporting editorial copy from the content already in WordPress.'),
    ),
    'compare' => array(
        array('AI rewrite for individual posts', 'Basic', 'Full workflow'),
        array('Headline generation', 'Limited', 'Multiple variations'),
        array('Summaries and excerpts', 'Basic', 'Advanced controls'),
        array('Tone and style controls', 'Limited presets', 'Full controls'),
        array('AI translation', 'No', 'Included'),
        array('Meta description generation', 'No', 'Included'),
        array('Custom prompt templates', 'No', 'Included'),
        array('Bulk content processing', 'No', 'Included'),
        array('Multiple AI providers', 'No', 'Supported providers'),
        array('Editorial review before apply', 'Yes', 'Yes'),
    ),
    'market' => array(
        array('WordPress editorial workflow', 'Core product focus', 0, 0),
        array('Rewrite existing WordPress articles', 'Built for this workflow', 1, 0),
        array('Headline variations', 'Editorial use case', 1, 0),
        array('Summaries and excerpts', 'Integrated with the post workflow', 1, 0),
        array('Translation workflow', 'Inside WordPress', 0, 0),
        array('Review before applying changes', 'Editorial control', 0, 0),
        array('Publisher and newsroom positioning', 'Primary audience', 0, 0),
    ),
    'plans' => array(
        '1-site' => 'For a single publication, blog or editorial website.',
        '5-sites' => 'For agencies, publishers and teams managing multiple WordPress sites.',
        'unlimited' => 'For agencies, publishing networks and larger WordPress operations.',
    ),
    'faq' => array(
        array('What is WSH AI News Editor PRO?', 'It is an AI-powered editorial assistant for WordPress publishers, news websites, magazines and content teams. It brings rewriting, summarization, headline generation, translation and content optimization into the WordPress editorial workflow.'),
        array('Is this plugin an automatic article generator?', 'No. Editors use AI actions, review the generated result and decide what should be applied or published.'),
        array('Can I rewrite an existing WordPress article?', 'Yes. Improve clarity, restructure a draft or prepare an alternative version while keeping the original topic and context.'),
        array('Can it generate headlines?', 'Yes. It generates multiple headline variations from an article so editors can compare different angles before selecting a final title.'),
        array('Can it create summaries and excerpts?', 'Yes. It turns longer content into concise summaries, excerpts and shorter versions for archive pages, newsletters or supporting content.'),
        array('Does it support translation?', 'Yes. PRO prepares additional language versions from inside WordPress so the team can review them before publication.'),
        array('Can I control tone and writing style?', 'Yes. Tone and style controls adapt the copy to different editorial requirements.'),
        array('Does it generate meta descriptions?', 'Yes. PRO generates concise meta descriptions from the article already in WordPress.'),
        array('Does AI publish changes automatically?', 'No. Generated text is reviewed before it replaces or updates the live article.'),
        array('Which AI provider does the plugin use?', 'PRO supports the AI providers included in the release. The settings screen shows which provider is connected.'),
        array('Do I need my own AI API key?', 'If the plugin is set up to use your provider account, that provider bills usage separately from the WSH license.'),
        array('Can I process multiple posts in bulk?', 'Yes. PRO can queue bulk actions so larger content libraries can be prepared and reviewed without opening every post by hand.'),
        array('Who is WSH AI News Editor PRO for?', 'News portals, online magazines, professional blogs, publishers, editorial teams, content agencies and other WordPress sites with a regular publishing workflow.'),
        array('What is included with a PRO license?', 'The annual site license you choose, PRO features, plugin updates and support while the subscription is active.'),
    ),
);
