<?php

return array(
    'slug' => 'bulk-price-manager',
    'title' => 'WSH WooCommerce Bulk Price Manager PRO',
    'needles' => array('bulk price manager'),
    'fields' => array(
        'landing_hero_label' => 'WSH WooCommerce Bulk Price Manager PRO',
        'landing_hero_title' => 'Update thousands of WooCommerce prices in minutes',
        'landing_hero_text' => 'Bulk increase, decrease, set and manage product prices across your WooCommerce catalog, with flexible filters and controlled pricing actions from one interface.',
        'landing_hero_primary' => 'Get PRO license',
        'landing_hero_secondary' => 'See all features',
        'landing_needs_label' => 'Why price management becomes a problem',
        'landing_needs_title' => 'Manual WooCommerce price updates do not scale.',
        'landing_needs_text' => 'Supplier costs change, promotions start and end, margins need protection and large catalogs require regular adjustments. WSH Bulk Price Manager PRO turns repetitive product-by-product pricing work into fast, controlled bulk operations.',
        'landing_features_label' => 'Features',
        'landing_features_title' => 'Professional WooCommerce pricing management from one dashboard',
        'landing_features_text' => 'Select the products you need, choose the pricing action, calculate the new values, review the result and apply changes across the catalog without editing products individually.',
        'landing_preview_label' => 'Preview',
        'landing_preview_title' => 'A clear workflow for large-scale price changes',
        'landing_preview_text' => 'Filter products, choose a price operation, enter the adjustment, preview old and new values, then apply or schedule the update.',
        'landing_compare_label' => 'Free vs PRO',
        'landing_compare_title' => 'Basic price editing is useful. PRO is built for serious catalog pricing.',
        'landing_compare_text' => 'The free edition covers simple bulk edits. PRO adds advanced filters, sale prices, variable products, preview and scheduled changes.',
        'landing_compare_free' => 'Bulk Price Manager (Free)',
        'landing_compare_pro' => 'Bulk Price Manager PRO',
        'landing_market_label' => 'Compare plugins',
        'landing_market_title' => 'How WSH Bulk Price Manager PRO fits into WooCommerce pricing',
        'landing_market_text' => 'A focused, safe pricing workflow for store owners and agencies that need repeatable catalog-wide price changes without spreadsheets or opening products one by one.',
        'landing_market_ours' => 'WSH Bulk Price Manager PRO',
        'landing_market_competitor_a' => 'WooCommerce native bulk edit',
        'landing_market_competitor_b' => 'Spreadsheet editors',
        'landing_pricing_label' => 'Pricing',
        'landing_pricing_title' => 'Choose your WSH WooCommerce Bulk Price Manager PRO license',
        'landing_pricing_text' => 'Simple annual licenses with updates and support included.',
        'landing_faq_label' => 'Frequently Asked Questions',
        'landing_faq_title' => 'Getting started with WSH Bulk Price Manager PRO',
        'landing_faq_button' => 'See more',
    ),
    'needs' => array(
        'You need to increase or decrease prices across hundreds of products at once.',
        'You want to apply percentage-based or fixed-value adjustments to selected products.',
        'You need to target the right products using categories, SKU, price, stock or other filters.',
        'You regularly create or remove sale prices across groups of products.',
        'You manage variable products and need a consistent bulk pricing workflow.',
        'You want to review calculated prices before committing a large catalog change.',
    ),
    'features' => array(
        array('tag' => 'Bulk editing', 'title' => 'Bulk price editing', 'text' => 'Update regular and sale prices across multiple WooCommerce products in a single workflow.'),
        array('tag' => 'Adjustments', 'title' => 'Percentage and fixed adjustments', 'text' => 'Increase or decrease prices using a percentage or a fixed amount when supplier costs, margins or the market change.'),
        array('tag' => 'Filters', 'title' => 'Advanced product filtering', 'text' => 'Target the exact products you want to change using the filters in the plugin, instead of editing the whole catalog.'),
        array('tag' => 'Sales', 'title' => 'Sale price management', 'text' => 'Create, update or remove promotional prices across selected product groups without opening products one by one.'),
        array('tag' => 'Variations', 'title' => 'Variable product support', 'text' => 'Run supported pricing operations for variable products and variations from the bulk workflow.'),
        array('tag' => 'Safety', 'title' => 'Preview before apply', 'text' => 'Review calculated price changes before they are committed to the live WooCommerce catalog.'),
    ),
    'compare' => array(
        array('Basic bulk price editing', 'Yes', 'Yes'),
        array('Percentage adjustments', 'Basic', 'Advanced'),
        array('Fixed-value adjustments', 'Basic', 'Advanced'),
        array('Advanced product filters', 'Limited', 'Included'),
        array('Sale price management', 'Limited', 'Included'),
        array('Variable products and variations', 'Limited', 'Full workflow'),
        array('Price rounding rules', 'No', 'Included'),
        array('Preview before apply', 'Basic', 'Advanced preview'),
        array('Scheduled price changes', 'No', 'Included'),
        array('Price history and rollback', 'No', 'Included'),
    ),
    'market' => array(
        array('Focused pricing workflow', 'Core product focus', 0, 0),
        array('Percentage and fixed adjustments', 'Key workflow', 0, 1),
        array('Advanced product targeting', 'PRO focus', 0, 1),
        array('Sale-price operations', 'Dedicated workflow', 0, 0),
        array('Preview calculated prices', 'Safety focus', 0, 0),
        array('Scheduling', 'PRO workflow', 0, 0),
        array('Simple WooCommerce administration', 'Key product goal', 1, 0),
    ),
    'plans' => array(
        '1-site' => 'For one WooCommerce store with ongoing pricing-management needs.',
        '5-sites' => 'For agencies, retailers and teams managing multiple WooCommerce stores.',
        '25-sites' => 'For WooCommerce agencies and professional multi-store operations.',
    ),
    'faq' => array(
        array('What is WSH WooCommerce Bulk Price Manager PRO?', 'It is a WooCommerce pricing plugin that updates prices across many products from one bulk workflow.'),
        array('Who is the plugin designed for?', 'WooCommerce store owners, wholesalers, online retailers, dropshipping businesses, catalog managers and agencies that regularly manage product pricing.'),
        array('Can I increase or decrease many prices at once?', 'Yes. Apply a percentage or a fixed amount to the products you select, without editing them one by one.'),
        array('Can I set an exact price for selected products?', 'Yes. You can set a specific price on the products in the current selection.'),
        array('Can I filter which products will be updated?', 'Yes. Filters and selection limit a price operation to the right part of the catalog.'),
        array('Can I manage WooCommerce sale prices?', 'Yes. Create, change or remove sale prices across a group of products, and schedule them when a promotion has a start and end.'),
        array('Does it work with variable products?', 'Yes. Pricing operations can target variable products and their variations.'),
        array('Can I preview new prices before applying them?', 'Yes. Review the calculated old and new values before anything is saved to the catalog.'),
        array('Does it support price rounding?', 'Yes. Rounding rules keep percentage calculations on clean price points.'),
        array('Can I schedule price changes?', 'Yes. Schedule a price change for a promotion or a future supplier update.'),
        array('Can I undo a bulk price update?', 'Yes. PRO keeps the previous prices so a bulk change can be restored.'),
        array('Is it suitable for large WooCommerce catalogs?', 'Yes. It is built for stores that manage hundreds or thousands of products.'),
        array('Will the plugin protect my profit margin automatically?', 'You choose the adjustment. The preview shows the new prices before they go live, so you can stop a change that would cut the margin too far.'),
        array('What is included with a PRO license?', 'The annual site license you choose, PRO functionality, plugin updates and support while the subscription is active.'),
    ),
);
