<?php

return array(
    'slug' => 'bulk-taxonomy-editor',
    'title' => 'WSH WooCommerce Bulk Taxonomy Editor PRO',
    'needles' => array('Bulk Taxonomy Editor'),
    'fields' => array(
        'landing_hero_label' => 'WSH WooCommerce Bulk Taxonomy Editor PRO',
        'landing_hero_title' => 'Organize your WooCommerce catalog in minutes',
        'landing_hero_text' => 'Bulk edit product categories, tags, attributes and supported taxonomies across hundreds or thousands of WooCommerce products, without opening them one by one.',
        'landing_hero_primary' => 'Get PRO license',
        'landing_hero_secondary' => 'See all features',
        'landing_needs_label' => 'Why catalog organization becomes a problem',
        'landing_needs_title' => 'Large WooCommerce catalogs make manual taxonomy editing painfully slow.',
        'landing_needs_text' => 'As a store grows, category structures change, imports create inconsistent tags, attributes need cleanup and products must be reorganized. WSH Bulk Taxonomy Editor PRO turns those repetitive product-by-product changes into controlled bulk operations.',
        'landing_features_label' => 'Features',
        'landing_features_title' => 'Professional bulk taxonomy management for WooCommerce',
        'landing_features_text' => 'Filter the products you need, choose the taxonomy operation, review the target set and apply catalog changes from one centralized workflow.',
        'landing_preview_label' => 'Preview',
        'landing_preview_title' => 'A clear workflow for large catalog changes',
        'landing_preview_text' => 'Filter products, select the target items, choose the taxonomy and operation, review the intended change, then apply it across the selected catalog.',
        'landing_compare_label' => 'Free vs PRO',
        'landing_compare_title' => 'Basic catalog editing is useful. PRO is built for serious bulk management.',
        'landing_compare_text' => 'The free edition covers basic selection and simple category edits. PRO adds filters, replace actions, attributes and a safer review step.',
        'landing_compare_free' => 'Bulk Taxonomy Editor (Free)',
        'landing_compare_pro' => 'Bulk Taxonomy Editor PRO',
        'landing_market_label' => 'Compare plugins',
        'landing_market_title' => 'How WSH Bulk Taxonomy Editor PRO fits into WooCommerce catalog management',
        'landing_market_text' => 'Focused taxonomy management rather than a general spreadsheet: target products, change their structure and keep the catalog clean from a purpose-built WooCommerce workflow.',
        'landing_market_ours' => 'WSH Bulk Taxonomy Editor PRO',
        'landing_market_competitor_a' => 'WooCommerce native bulk edit',
        'landing_market_competitor_b' => 'Spreadsheet tools',
        'landing_pricing_label' => 'Pricing',
        'landing_pricing_title' => 'Choose your WSH WooCommerce Bulk Taxonomy Editor PRO license',
        'landing_pricing_text' => 'Simple annual licenses with updates and support included.',
        'landing_faq_label' => 'Frequently Asked Questions',
        'landing_faq_title' => 'Getting started with WSH Bulk Taxonomy Editor PRO',
        'landing_faq_button' => 'See more',
    ),
    'needs' => array(
        'You need to assign or remove categories across hundreds of products at once.',
        'You want to clean up inconsistent tags created by imports, suppliers or old catalog structures.',
        'You need to reorganize product attributes without opening every product individually.',
        'You manage a large catalog and need powerful filters to target the exact products you want to change.',
        'You want separate Add, Remove and Replace actions instead of blindly overwriting existing taxonomy data.',
        'You run a store or agency where catalog maintenance must be fast, repeatable and easy for administrators.',
    ),
    'features' => array(
        array('tag' => 'Bulk editing', 'title' => 'Bulk taxonomy editing', 'text' => 'Update categories, tags, attributes and supported product taxonomies across multiple WooCommerce products in a single operation.'),
        array('tag' => 'Filters', 'title' => 'Advanced product filtering', 'text' => 'Find the exact products you want to modify using the plugin filters, instead of editing the entire catalog.'),
        array('tag' => 'Categories', 'title' => 'Categories and tags', 'text' => 'Add, remove, replace and reorganize product categories and tags without opening products individually.'),
        array('tag' => 'Attributes', 'title' => 'Product attribute management', 'text' => 'Manage WooCommerce product attributes across selected products from one administration interface.'),
        array('tag' => 'Actions', 'title' => 'Add, Remove and Replace', 'text' => 'Append new terms, remove obsolete terms or replace one structure with another.'),
        array('tag' => 'Scale', 'title' => 'Large catalog workflow', 'text' => 'Reduce repetitive catalog work when managing hundreds or thousands of WooCommerce products.'),
    ),
    'compare' => array(
        array('Basic product selection', 'Yes', 'Yes'),
        array('Category bulk editing', 'Basic', 'Advanced workflow'),
        array('Tags bulk editing', 'Basic', 'Advanced workflow'),
        array('Product attributes', 'Limited', 'Full workflow'),
        array('Advanced product filters', 'Limited', 'Included'),
        array('Add taxonomy terms', 'Yes', 'Yes'),
        array('Remove taxonomy terms', 'Limited', 'Included'),
        array('Replace taxonomy terms', 'No', 'Included'),
        array('Custom product taxonomies', 'No', 'Included'),
        array('Change preview', 'Basic', 'Included'),
    ),
    'market' => array(
        array('Focused taxonomy workflow', 'Core product focus', 0, 0),
        array('Categories and tags', 'Advanced bulk actions', 0, 1),
        array('Product attributes', 'Supported workflow', 0, 0),
        array('Add, Remove and Replace', 'Key workflow', 0, 0),
        array('Advanced product targeting', 'PRO focus', 0, 1),
        array('Catalog cleanup', 'Primary focus', 0, 0),
        array('Simple WooCommerce administration', 'Key product goal', 1, 0),
    ),
    'plans' => array(
        '1-site' => 'For one WooCommerce store with ongoing catalog-management needs.',
        '5-sites' => 'For agencies, retailers and teams managing multiple WooCommerce stores.',
        '25-sites' => 'For WooCommerce agencies and professional multi-site catalog operations.',
    ),
    'faq' => array(
        array('What is WSH WooCommerce Bulk Taxonomy Editor PRO?', 'It is a WooCommerce catalog plugin that bulk edits product categories, tags, attributes and supported taxonomies without opening products one by one.'),
        array('Who is the plugin designed for?', 'WooCommerce store owners, wholesalers, dropshipping businesses, catalog managers and agencies that maintain medium or large product catalogs.'),
        array('What can I edit in bulk?', 'Categories, tags, product attributes and the product taxonomies the plugin supports.'),
        array('Can I add taxonomy terms without removing existing ones?', 'Yes. Add appends the selected terms and leaves the current assignments in place.'),
        array('Can I remove categories or tags from many products at once?', 'Yes. Target the products you want and remove the chosen terms.'),
        array('Can I replace one category, tag or term with another?', 'Yes. Replace is the PRO action for restructuring a catalog, swapping one term for another across the selection.'),
        array('How do I choose which products will be changed?', 'Filters and selection limit the operation to the target set, not the whole store.'),
        array('Does it work with product attributes?', 'Yes. Supported global and product attributes can be updated across the selected products.'),
        array('Does it support custom taxonomies?', 'Yes. PRO edits the product taxonomies it detects on the store, including custom ones registered for products.'),
        array('Can I preview changes before applying them?', 'Yes. Review the target products and the intended taxonomy change before it is applied.'),
        array('Can I review a change before it is applied?', 'Yes. Preview shows the current terms and the result. Apply only after that looks right. The plugin does not roll a change back automatically.'),
        array('Is it suitable for large product catalogs?', 'Yes. It is intended for stores managing hundreds or thousands of products.'),
        array('Will it work with variable products?', 'Yes. Taxonomy operations run on the parent products that carry categories, tags and attributes.'),
        array('What is included with a PRO license?', 'The annual site license you choose, PRO functionality, plugin updates and support while the subscription is active.'),
    ),
);
