<?php

return array(
    'slug' => 'product-catalog',
    'title' => 'WSH Product Catalog PRO',
    'needles' => array('WSH Product Catalog'),
    'fields' => array(
        'landing_hero_label' => 'WSH Product Catalog PRO',
        'landing_hero_title' => 'One WooCommerce catalog. Multiple sales channels.',
        'landing_hero_text' => 'Create, organize and distribute WooCommerce product data for Google, Meta and other external sales and advertising channels from one centralized workflow.',
        'landing_hero_primary' => 'Get PRO license',
        'landing_hero_secondary' => 'See all features',
        'landing_needs_label' => 'Why catalog management becomes difficult',
        'landing_needs_title' => 'Your WooCommerce data is ready for your store, not necessarily for every external channel.',
        'landing_needs_text' => 'Each marketplace and advertising platform expects structured product data. WSH Product Catalog PRO helps store owners and agencies select the right products, map WooCommerce fields, organize external categories and keep channel feeds aligned with the store catalog.',
        'landing_features_label' => 'Features',
        'landing_features_title' => 'A centralized WooCommerce catalog workflow',
        'landing_features_text' => 'Build channel-ready product catalogs from the data you already maintain in WooCommerce. Filter products, map data, validate required information and generate structured outputs from one administration area.',
        'landing_preview_label' => 'Preview',
        'landing_preview_title' => 'Manage products, mappings and feeds from one WooCommerce interface',
        'landing_preview_text' => 'Select the products, map product fields and categories, validate the data, preview the output and generate or update the catalog.',
        'landing_compare_label' => 'Free vs PRO',
        'landing_compare_title' => 'Start with basic feed generation. Unlock professional catalog management with PRO.',
        'landing_compare_text' => 'The free edition covers a basic product export. PRO adds multiple catalogs, field and category mapping, validation and channel-ready feeds.',
        'landing_compare_free' => 'WSH Product Catalog (Free)',
        'landing_compare_pro' => 'WSH Product Catalog PRO',
        'landing_market_label' => 'Compare plugins',
        'landing_market_title' => 'How WSH Product Catalog PRO fits into the WooCommerce feed market',
        'landing_market_text' => 'Centralized catalog control: product selection, mapping, validation and feed management in a WordPress-native interface.',
        'landing_market_ours' => 'WSH Product Catalog PRO',
        'landing_market_competitor_a' => 'Basic feeds',
        'landing_market_competitor_b' => 'Enterprise platforms',
        'landing_pricing_label' => 'Pricing',
        'landing_pricing_title' => 'Choose your WSH Product Catalog PRO license',
        'landing_pricing_text' => 'Simple annual licenses with updates and support included.',
        'landing_faq_label' => 'Frequently Asked Questions',
        'landing_faq_title' => 'Getting started with WSH Product Catalog PRO',
        'landing_faq_button' => 'See more',
    ),
    'needs' => array(
        'You want to send WooCommerce products to Google and Meta without maintaining separate spreadsheets.',
        'You need precise control over which products, categories or stock states are included in each catalog.',
        'You need to map WooCommerce product fields to channel-specific attributes.',
        'You want to catch missing or incomplete product information before generating a feed.',
        'You manage variable products and need consistent product, price and stock data.',
        'You want catalog updates to follow changes in WooCommerce instead of rebuilding feeds manually.',
    ),
    'features' => array(
        array('tag' => 'Catalogs', 'title' => 'Multi-channel product catalogs', 'text' => 'Create separate catalog configurations for supported advertising and commerce channels while keeping WooCommerce as the product-data source.'),
        array('tag' => 'Filtering', 'title' => 'Advanced product filtering', 'text' => 'Choose which products belong in a catalog using categories, tags, product type, stock status, price and other WooCommerce data.'),
        array('tag' => 'Mapping', 'title' => 'Product field mapping', 'text' => 'Map WooCommerce titles, descriptions, images, prices and other fields to the attributes expected by an external channel.'),
        array('tag' => 'Categories', 'title' => 'Category mapping', 'text' => 'Connect WooCommerce product categories with supported external taxonomy structures so products can be classified correctly.'),
        array('tag' => 'Validation', 'title' => 'Catalog data validation', 'text' => 'Identify missing or incomplete product information before feed generation and reduce avoidable catalog errors.'),
        array('tag' => 'Updates', 'title' => 'Feeds from live store data', 'text' => 'Each feed is built from the current WooCommerce catalog, so the next request already includes the latest products, prices and stock.'),
    ),
    'compare' => array(
        array('Basic WooCommerce product export', 'Yes', 'Yes'),
        array('Catalog configurations', 'Single', 'Multiple configurations'),
        array('Advanced product filtering', 'Limited', 'Advanced rules'),
        array('Product field mapping', 'Basic', 'Advanced mapping'),
        array('Category mapping', 'No', 'Included'),
        array('Variable product support', 'Limited', 'Full workflow'),
        array('Catalog validation', 'Basic', 'Advanced validation'),
        array('Live catalog data', 'Manual export', 'Feed reflects the current store'),
        array('XML and CSV feed outputs', 'Limited', 'Supported formats'),
        array('Multiple external channels', 'Limited', 'Supported PRO channels'),
    ),
    'market' => array(
        array('WooCommerce-native workflow', 'Core focus', 1, 0),
        array('Advanced product selection', 'Designed for PRO', 0, 1),
        array('Field mapping', 'Central workflow', 0, 1),
        array('Category mapping', 'PRO capability', 0, 1),
        array('Catalog validation', 'Integrated into the workflow', 0, 1),
        array('Feed from the current catalog', 'Supported workflow', 0, 1),
        array('Simple WordPress administration', 'Key product goal', 1, 0),
    ),
    'plans' => array(
        '1-site' => 'For one WooCommerce store.',
        '5-sites' => 'For agencies, retailers and teams managing multiple stores.',
        '25-sites' => 'For WooCommerce agencies, store networks and professional implementations.',
    ),
    'faq' => array(
        array('What is WSH Product Catalog PRO?', 'It is a WooCommerce catalog and product-feed plugin that prepares product data for supported sales and advertising channels from WordPress.'),
        array('Which platforms can I use it with?', 'Google and Meta are the core channels. The plugin lists the feed specifications included in your version.'),
        array('Does the plugin change my WooCommerce products?', 'No. WooCommerce stays the source of product data. Mapping and feed settings do not change the original product unless you edit it yourself.'),
        array('Can I choose which products are included in a catalog?', 'Yes. Filters decide which products are included or excluded, using categories, tags, stock, price and other WooCommerce data.'),
        array('Can I map WooCommerce fields to external catalog fields?', 'Yes. Field mapping connects titles, descriptions, images, prices and other WooCommerce data with the attributes a channel expects.'),
        array('Does it support category mapping?', 'Yes. PRO maps WooCommerce categories to the external taxonomy used by the channel.'),
        array('Does it support variable products?', 'Yes. Parent products and variations are included in the export for each supported channel.'),
        array('Can the plugin detect missing product data?', 'Yes. Validation highlights missing or incomplete information before you export.'),
        array('Do I have to rebuild the feed after every product change?', 'No. The feed is generated from the current WooCommerce catalog, so a new request already includes the latest products, prices and stock.'),
        array('Which feed formats are supported?', 'PRO generates the XML and CSV feeds included in the release.'),
        array('Do I need a Google or Meta account?', 'Yes, for those channels. The merchant or advertising account is separate from the WSH license and follows that platform\'s own rules.'),
        array('Does the plugin guarantee product approval by Google or Meta?', 'No. It helps structure and validate product data. Final acceptance is decided by the external platform.'),
        array('Is it suitable for large WooCommerce catalogs?', 'Yes. It is built for stores and agencies that manage large catalogs from one WordPress workflow.'),
        array('What is included with a PRO license?', 'The annual site license you choose, PRO functionality, plugin updates and support while the subscription is active.'),
    ),
);
