<?php

return array(
    'slug' => 'quiz',
    'title' => 'WSH Quiz',
    'needles' => array('WSH Quiz'),
    'fields' => array(
        'landing_hero_label' => 'WSH Quiz PRO',
        'landing_hero_title' => 'Turn your WordPress content into interactive experiences',
        'landing_hero_text' => 'Create engaging quizzes, tests and knowledge challenges directly in WordPress with flexible scoring, customizable results and an easy-to-use workflow.',
        'landing_hero_primary' => 'Get PRO license',
        'landing_hero_secondary' => 'See all features',
        'landing_needs_label' => 'Why interactive content matters',
        'landing_needs_title' => 'Publishing content is easy. Getting visitors to participate is harder.',
        'landing_needs_text' => 'WSH Quiz PRO helps turn readers into active participants. Instead of asking visitors to only read and leave, add quizzes and tests that encourage interaction, repeat visits and deeper engagement with your content.',
        'landing_features_label' => 'Features',
        'landing_features_title' => 'Everything you need to build engaging WordPress quizzes',
        'landing_features_text' => 'WSH Quiz PRO combines quiz creation, question management, scoring and publishing tools in one WordPress-native workflow.',
        'landing_preview_label' => 'Preview',
        'landing_preview_title' => 'A clean quiz workflow for creators and site administrators',
        'landing_preview_text' => 'Create the quiz, organize questions and answers, configure scoring and results, then publish it on your WordPress site from one streamlined workflow.',
        'landing_compare_label' => 'Free vs PRO',
        'landing_compare_title' => 'Start simple. Unlock advanced quiz workflows with PRO.',
        'landing_compare_text' => 'The free edition covers basic quizzes. PRO adds flexible scoring, advanced results, image and video questions and attempt reports.',
        'landing_compare_free' => 'WSH Quiz (Free)',
        'landing_compare_pro' => 'WSH Quiz PRO',
        'landing_market_label' => 'Compare plugins',
        'landing_market_title' => 'How WSH Quiz PRO fits into the WordPress quiz market',
        'landing_market_text' => 'A clean WordPress-native workflow, straightforward quiz creation and a focused feature set, without the complexity of a large quiz suite.',
        'landing_market_ours' => 'WSH Quiz PRO',
        'landing_market_competitor_a' => 'Large quiz suites',
        'landing_market_competitor_b' => 'Basic quiz plugins',
        'landing_pricing_label' => 'Pricing',
        'landing_pricing_title' => 'Choose your WSH Quiz PRO license',
        'landing_pricing_text' => 'Simple annual licenses with updates and support included.',
        'landing_faq_label' => 'Frequently Asked Questions',
        'landing_faq_title' => 'Getting started with WSH Quiz PRO',
        'landing_faq_button' => 'See more',
    ),
    'needs' => array(
        'You want visitors to interact with your content instead of only reading it.',
        'You need a simple way to build quizzes and tests without custom development.',
        'You want flexible scoring and result messages for different quiz outcomes.',
        'You manage educational, editorial or marketing content and need reusable question workflows.',
        'You want quizzes that work smoothly across desktop, tablet and mobile devices.',
        'You want to publish quizzes anywhere in WordPress using a straightforward editor and embedding workflow.',
    ),
    'features' => array(
        array('tag' => 'Builder', 'title' => 'Flexible quiz builder', 'text' => 'Create and manage professional quizzes and tests directly from the WordPress dashboard without writing code.'),
        array('tag' => 'Questions', 'title' => 'Multiple question types', 'text' => 'Build richer quizzes using supported question and answer formats, with clear controls for creating and organizing questions.'),
        array('tag' => 'Scoring', 'title' => 'Custom scoring system', 'text' => 'Assign scores to answers and control how the final quiz result is calculated.'),
        array('tag' => 'Results', 'title' => 'Custom quiz results', 'text' => 'Show tailored result messages based on a participant\'s performance or score.'),
        array('tag' => 'Analytics', 'title' => 'Attempts and scores', 'text' => 'See who took the quiz, how they scored and how many people finished it.'),
        array('tag' => 'Publishing', 'title' => 'Easy WordPress integration', 'text' => 'Publish quizzes inside posts, pages and other supported areas using the plugin\'s WordPress integration tools.'),
    ),
    'compare' => array(
        array('Create and publish quizzes', 'Yes', 'Yes'),
        array('Basic question management', 'Yes', 'Advanced controls'),
        array('Scoring', 'Basic', 'Flexible scoring'),
        array('Custom result messages', 'Limited', 'Advanced results'),
        array('Image and video questions', 'No', 'Included'),
        array('Quiz styling options', 'Basic', 'Advanced customization'),
        array('Multiple rounds', 'No', 'Included'),
        array('Quiz analytics and attempts', 'No', 'Included'),
        array('Name and email before the quiz', 'Yes', 'Yes'),
        array('Priority updates and support', 'No', 'Included'),
    ),
    'market' => array(
        array('WordPress-native quiz workflow', 'Core focus', 1, 1),
        array('Flexible scoring', 'Designed for the PRO workflow', 1, 0),
        array('Custom result experiences', 'PRO focus', 1, 0),
        array('Attempt analytics', 'PRO capability', 1, 0),
        array('Ease of administration', 'Key product goal', 0, 1),
        array('Publisher and content use cases', 'Primary target', 1, 1),
        array('Article-to-quiz workflow with AI News Editor', 'Built for the WPPluginsPro ecosystem', 0, 0),
    ),
    'plans' => array(
        '1-site' => 'For one blog, educational site, publication or marketing website.',
        '5-sites' => 'For agencies, publishers and teams managing multiple WordPress sites.',
        '25-sites' => 'For agencies, networks and professional WordPress operations.',
    ),
    'faq' => array(
        array('What is WSH Quiz PRO?', 'WSH Quiz PRO is a WordPress plugin for creating interactive quizzes and tests directly from the dashboard, with tools for questions, answers, scoring, results and publishing.'),
        array('Who is WSH Quiz PRO designed for?', 'It is designed for bloggers, publishers, educational websites, online magazines, marketers, teachers, content creators and WordPress site owners who want to add interactive content.'),
        array('Do I need coding knowledge to create a quiz?', 'No. Quizzes are created and managed from a WordPress-native administration screen, without custom coding.'),
        array('Can I create different types of questions?', 'Yes. The plugin supports multiple question and answer formats so you can build richer quizzes and keep them organized.'),
        array('Can I control quiz scoring?', 'Yes. Answers can contribute to the participant\'s final result through configurable scoring.'),
        array('Can I customize the result shown after a quiz?', 'Yes. Result messages can be configured according to the score or outcome.'),
        array('Can questions include images and video?', 'Yes. PRO adds image prompts, video prompts and image answers on top of standard questions.'),
        array('Can I place quizzes inside WordPress posts and pages?', 'Yes. Publish a quiz inside posts and pages with the plugin\'s WordPress integration.'),
        array('Will quizzes work on mobile devices?', 'Yes. The quiz frontend is responsive, so people can complete a quiz on desktop, tablet and mobile.'),
        array('Can I use WSH Quiz PRO for educational tests?', 'Yes. The question, scoring and result workflow is a fit for educational and knowledge-testing sites.'),
        array('Can I use it for publishers and news websites?', 'Yes. Quizzes complement editorial content on news portals, magazines and blogs.'),
        array('Does WSH Quiz PRO include quiz analytics?', 'Yes. PRO stores and reports attempts, scores and completions.'),
        array('Will it work with other WPPluginsPro products?', 'Yes. A coming connection with AI News Editor will let publishers turn existing articles into quiz questions. Until that ships, each plugin works on its own.'),
        array('What is included with a PRO license?', 'The annual site license you choose, PRO functionality, plugin updates and support while the subscription is active.'),
    ),
);
